name: Terraform Apply (Kubernetes Infra)

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      # AWS credentials
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            us-east-1

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init -input=false

      # Importa recursos existentes, se necessários
      - name: Import cluster / nodegroup / secret if missing
        run: |
          terraform state list | grep -q '^aws_eks_cluster\.eks$' || \
            terraform import aws_eks_cluster.eks academy-cluster
          terraform state list | grep -q '^aws_eks_node_group\.node_group$' || \
            terraform import aws_eks_node_group.node_group academy-cluster:academy-node-group || true
          terraform state list | grep -q '^aws_secretsmanager_secret\.eks_info$' || \
            terraform import aws_secretsmanager_secret.eks_info $(aws secretsmanager list-secrets --region us-east-1 --query "SecretList[?Name=='eks-academy-cluster-info'].[ARN]" --output text) || true

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve tfplan

      - name: Generate kubeconfig
        run: aws eks update-kubeconfig --name academy-cluster --region us-east-1
